KnisterPeter/vscode-github

- src/git.ts
Supersedes #37 
* This as well allow git@github.com:user/repo.git
* For tsc to allow potential null values
> fix: correctly obtain Git remote and parse it

- README.md
- package.json
- src/extension.ts
- src/github-manager.ts
- src/github.ts
This implements a more complex pull request creation strategy which enables creating pull requests
in forked repositories.
ISSUES CLOSED: #58
> feat: create PR for fork

- package.json
- src/extension.ts
- src/github-manager.ts
Add command to open project on github.com
Closes #70
> feat(vscode-github): add command to open github page

- src/extension.ts
After successful creation of pull request allow to open it on github
Closes #69
> feat(vscode-github): allow to open pull request

- package.json
> fix(vscode-github): update pretend

- package.json
- src/extension.ts
- src/github-manager.ts
- src/github.ts
Allow to add and remove assignees to or from the current pull request
Closes #71
> feat(vscode-github): allow to manage PR assignees

- README.md
- package.json
- src/extension.ts
- src/github-manager.ts
- src/github.ts
Allow to create and cancel pull request reviews
Closes #83
> feat(vscode-github): manage pull request reviews

- src/extension.ts
- src/git.ts
Notify user to push branch before creating pull request
Closes #61
> fix: handle local only branches

- package.json
- src/extension.ts
- src/git.ts
- src/github-manager.ts
- src/github.ts
> feat: use vscode git extension to checkout treeish

- package.json
- src/extension.ts
- src/git.ts
- src/github-manager.ts
- test/extension.test.ts
> feat: add vscode progress-ui to long running operations

- package.json
- src/extension.ts
> feat: open pull request of current branch

- src/extension.ts
- src/git.ts
- src/github-manager.ts
- src/github.ts
Refactored spread of github hostname through the extension to be
centrally at entry point
> refactor: prepare for github enterprise support

- README.md
- package.json
- src/extension.ts
- src/git.ts
- src/github-manager.ts
> feat: github enterprise support

- package.json
- src/extension.ts
- src/github-manager.ts
- src/github.ts
> feat: browse open issues

- src/github-manager.ts
> fix: respect protcol in hostnames

- package.json
- src/extension.ts
- src/github-manager.ts
> feat: browsing current file

- src/git.ts
- test/extension.test.ts
> fix: parsing git url

- .travis.yml
- package.json
- src/extension.ts
To improve error tracking and debugability all errors are logged with
stacktrace to the github channel now
> feat: error logging

- src/github.ts
Add api call to fetch pull request comments
> feat: extend github api

- src/extension.ts
Enables the selection of a branch during creation of a pull request.
To use this feature the command 'Create pull request...' must be
executed and after the repository selection the branch selection is
shown. The branch shown by default is the github default branch of the
selected repository.
Closes #125
> feat: allow to select branch for pull request

- README.md
- package-lock.json
- package.json
- src/extension.ts
Updates to run this on vscode 1.14
> fix: update for vscode 1.14

- package.json
Eager activation of extension to get around multiple cases where
commands should be available but the extension was not activated
Closes #136
> fix: eager activation of extension commands

- README.md
- package-lock.json
- src/extension.ts
Do not spam error output to users if there is no workspace available
Closes #142
> fix: do not error in empty workspaces

- package.json
- src/git.ts
Configure the remote name per configuration setting 'github.remoteName'
Closes #145
> feat: allow to configure remote name

- package-lock.json
- package.json
- src/extension.ts
- src/github-manager.ts
- src/status-bar-manager.ts
For future compatibility the workspaceFolder APIs are used from now.
This does not mean there is support for multi-folder projects tho.
Closes #151
> refactor: update to workspace folders

- package-lock.json
- package.json
- src/command-manager.ts
- src/command.ts
- src/commands/browse.ts
- src/commands/pull-requests.ts
- src/commands/token.ts
- src/commands/user.ts
- src/extension.ts
- src/github-manager.ts
- src/helper.ts
- src/main.ts
- src/status-bar-manager.ts
- tsconfig.json
Use dependency injection to have a better strucutured base and
simplicity for future extensions
> refactor: rewrite internal structure

- package-lock.json
- src/commands/pull-requests.ts
> feat: checkout pull request by number

- README.md
- package.json
- src/extension.ts
- src/status-bar-manager.ts
For customization the status bar command is configurable to any known
command.
Closes #140
> feat: add configurable status bar

- .travis.yml
- package-lock.json
- package.json
- src/extension.ts
- src/main.ts
To gain usage insides the appinside telemetry reporter is used
> feat: add telemetry tool

- package.json
> fix(package): update tsdi to version 0.14.0

- src/commands/pull-requests.ts
> fix typo in warning message

- src/commands/pull-requests.ts
- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/index.ts
- src/provider/github/repository.ts
- src/provider/repository.ts
- src/workflow-manager.ts
Create abstraction for repository access to migrate to multi-provider
support
> refactor: abstract access to repository

- src/commands/pull-requests.ts
- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/index.ts
- src/provider/github/pull-request.ts
- src/provider/pull-request.ts
- src/status-bar-manager.ts
- src/workflow-manager.ts
Rewrite pull request handling to migrate to multi provider support
> refactor: rewrite pull request handling

- src/provider/client.ts
- src/provider/github/client.ts
- src/workflow-manager.ts
Reimplement merging to support multiple providers.
> refactor: reimplement merging to support multiple providers

- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/pull-request.ts
- src/provider/github/repository.ts
- src/provider/pull-request.ts
- src/provider/repository.ts
- src/workflow-manager.ts
For natural usage the provider api is object oriented.
> refactor: more object oriented api for providers

- src/status-bar-manager.ts
- src/workflow-manager.ts
> refactor: simplified pull request status

- README.md
- package-lock.json
- package.json
- src/commands/user.ts
- src/provider/github/index.ts
- src/provider/github/pull-request.ts
- src/provider/github/user.ts
- src/provider/pull-request.ts
- src/provider/user.ts
- src/workflow-manager.ts
To support multi provider interface rework of assignees is necessary
> refactor: reimplement assignee handling

- src/commands/browse.ts
- src/provider/github/repository.ts
- src/provider/issue.ts
- src/provider/repository.ts
- src/workflow-manager.ts
To support multi provider api issues where reimplemented
> refactor: reimplement issues

- src/provider/github/pull-request.ts
- src/provider/pull-request.ts
- src/workflow-manager.ts
> refactor: reimplement pull request comments

- src/provider/github/client.ts
- src/provider/github/repository.ts
- src/provider/repository.ts
- src/workflow-manager.ts
> refactor: cleanup workflow manager

- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/repository.ts
- src/provider/gitlab/user.ts
> feat: add interfaces and stubs for gitlab

- README.md
- package.json
- src/commands/pull-requests.ts
- src/commands/token.ts
- src/git.ts
- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/repository.ts
- src/provider/gitlab/user.ts
- src/workflow-manager.ts
Refactor provider connection to support different providers
> feat: connect to different providers

- src/git.ts
- src/provider/client.ts
- src/provider/github/index.ts
- src/provider/github/repository.ts
- src/provider/gitlab/repository.ts
- src/provider/repository.ts
- src/workflow-manager.ts
- test/extension.test.ts
> feat: add browse project for gitlab

- .vscode/settings.json
- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/repository.ts
- src/workflow-manager.ts
> feat: list merge requests on a project

- src/provider/gitlab/api.ts
- src/provider/gitlab/repository.ts
> feat: load single merge request

- src/provider/gitlab/api.ts
- src/provider/gitlab/repository.ts
> feat: enable gitlab support for creating merge request

- src/git.ts
- src/workflow-manager.ts
> fix: currect lookup of first commit on branch

- src/commands/token.ts
Fix erroneous removal of github enterprise token command.
Closes #203
> fix: readd github enterpise token command

- package.json
- src/commands/pull-requests.ts
- src/configuration.ts
- src/git.ts
- src/helper.ts
- src/status-bar-manager.ts
The status bar could be colorless and the status texts could be adjusted as well.
There are three variables which could be used:
* ${icon}
* ${prNumber}
* ${status}
Closes #202
> feat: customizable statusbar

- src/commands/pull-requests.ts
- src/extension.ts
- src/git.ts
- src/provider/client.ts
- src/status-bar-manager.ts
- src/workflow-manager.ts
- test/extension.test.ts
For easier debugging and tracability every local git command is logged.
Relates to #207
> refactor: log all git commands

- package.json
- src/configuration.ts
- src/extension.ts
- src/git.ts
- src/status-bar-manager.ts
Add option to configure path to git executable.
Closes #210
> feat: add configuration for git executable

- package.json
- src/commands/token.ts
- src/tokens.ts
Add command to remove old or invalid tokens from registry/storage.
Closes #193
> feat: add remove token command

- package.json
- src/commands/pull-requests.ts
- src/configuration.ts
When creating a pull request, automatically publish the current branch before.
> feat: publish branch automatically

- src/provider/gitlab/api.ts
- src/provider/gitlab/repository.ts
> feat: add support for gitlab issues

- package.json
- src/configuration.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/repository.ts
Add GitLab feature 'remove_source_branch' to provider.
> feat: add support for remove_source_branch

- package.json
- src/configuration.ts
- src/helper.ts
- src/provider/gitlab/repository.ts
Use own toplevel gitlab settings
> refactor: move gitlab settings to toplevel

- src/commands/pull-requests.ts
- src/git.ts
Show a quick pick with all remote branches as target when creating pull request.
Closes #223
> feat: quick pick branches for pull request

- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/index.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- src/workflow-manager.ts
To get more information on errors during api calls, request method, url and response status are logged.
> feat: add request logging

- src/command.ts
- src/commands/browse.ts
- src/commands/pull-requests.ts
- src/commands/user.ts
- src/provider/github/index.ts
- src/provider/github/pull-request.ts
- src/provider/gitlab/merge-request.ts
- src/provider/pull-request.ts
- src/workflow-manager.ts
Add command to update pull request title and body.
> feat: add update pull request command

- src/provider/gitlab/api.ts
- src/provider/gitlab/merge-request.ts
Implement accept merge request api.
> feat: support merging in gitlab

- src/commands/user.ts
- src/provider/github/index.ts
- src/provider/github/repository.ts
- src/provider/gitlab/repository.ts
- src/provider/repository.ts
- src/workflow-manager.ts
> feat: provide list of assignees

- package.json
- src/command.ts
- src/commands/browse.ts
- src/commands/pull-requests.ts
- src/commands/token.ts
- src/commands/user.ts
- src/extension.ts
- src/git.ts
- src/helper.ts
- src/main.ts
- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/repository.ts
- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/repository.ts
- src/provider/repository.ts
- src/status-bar-manager.ts
- src/tokens.ts
- src/workflow-manager.ts
Add support for multi folder feature of vscode.
> feat: add multi folder support

- src/extension.ts
- src/issues.ts
- src/workflow-manager.ts
Add a link to issues when a matching comment is found
Closes #241
> feat: link to issues from source

- package-lock.json
- package.json
- src/issues.ts
- src/provider/github/index.ts
- src/provider/github/issue.ts
- src/provider/github/repository.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/issue.ts
- src/provider/gitlab/repository.ts
- src/provider/issue.ts
- src/workflow-manager.ts
Show issue and comments on hover
Closes #241
> feat: hover issue

- src/command.ts
- src/commands/pull-requests.ts
- src/extension.ts
- src/provider/client.ts
- src/provider/github/api.ts
- src/provider/github/client.ts
- src/provider/github/issue.ts
- src/provider/github/pull-request.ts
- src/provider/github/repository.ts
- src/provider/github/user.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- src/status-bar-manager.ts
- src/workflow-manager.ts
> feat: add test connect per provider

- src/status-bar-manager.ts
> fix: update status for single workspace

- package-lock.json
- src/provider/github/api.ts
Use duck-typing to determine error object.
Closes #278
> fix: do not assume github error

- .vscode/launch.json
- .vscode/tasks.json
- package-lock.json
- src/provider/client.ts
- src/workflow-manager.ts
- test/extension.test.ts
> refactor: add log if token connect fails

- README.md
> Add documentation about settings & clean up typos in readme

- package-lock.json
- src/commands/user.ts
For programatic usage of the user commands, user parameters are added.
> feat: add parameters to user commands

- package.json
> fix(package): update tsdi to version 0.19.2

- package-lock.json
- package.json
- src/configuration.ts
- src/provider/client.ts
- src/provider/github/api.ts
- src/provider/github/client.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- typings/fetch-extras.d.ts
Superseeds #306 and includes it.
Closes #306
> fix: add agent to global RequestInit interface

- src/provider/github/client.ts
To reduce server load for GHE instances the repository
data is aggressively cached per workspace and gitconfig.
Closes #356
> fix: cache repository data per workspace and gitconfig

- src/status-bar-manager.ts
> fix: set statusbar item priority

- src/commands/browse.ts
- src/git.ts
> fix: browser current file respect git root

- package.json
- src/configuration.ts
- src/git.ts
- src/workflow-manager.ts
Adds a new feature to input a custom pull request title as reported here: #338
> Custom title when creating a new pull request

- .vscode/settings.json
- package.json
- src/command.ts
- src/git.ts
- src/status-bar-manager.ts
- src/workflow-manager.ts
- tslint.json
- yarn.lock
> feat: show and explain error for invalid git remotes

- src/commands/token.ts
- src/extension.ts
- src/provider/client.ts
- src/tokens.ts
- src/workflow-manager.ts
> fix: allow tokens to be updated during runtime

- src/issues.ts
> fix: disble issue scanning for now

- .github/workflows/duplicate.yml
Auto-flag and close cpu issues
> chore: duplicate workflow

- src/commands/pull-requests.ts
A really small, simple PR.
Feedback would be appreciated.
After this one, I may add 1 or 2 more features.
> Make Pull Request creation more User-Friendly
