- README.md
- package.json
- src/extension.ts
- src/github.ts
It would be nice if this extension offered a command to browse an open PR for the current branch. Currently I'm using this custom git command to accomplish this on the command line:
```bash
#!/bin/bash
#
set -e
branch="${1:-$(git symbolic-ref HEAD)}"
branch="${branch#refs/heads/}"
remote_url() {
git remote -v | grep "^$1" | head -1 | grep -o 'github.com[/:]\S\+'
}
url="$(remote_url upstream || true)"
url="${url:-$(remote_url github || true)}"
url="${url:-$(remote_url origin || true)}"
url="${url%.git}"
open "https://${url/://}/pull/${branch//\//%2F}"
```
> Feature request: Go to open PR

- package.json
- src/git.ts
To make working with upstream repositories (forks) easier it is possible to
set `github.upstream` now. This must be a github slug
(e.g. microsoft/typescript) which is used for all github communication then.
Closes #31
> feat: allow setting of upstream repo

- src/extension.ts
- src/git.ts
- src/github-manager.ts
Add commit body of first commit in branch as body to the pull request
> feat: add pull request body

- README.md
- package.json
- src/extension.ts
- src/git.ts
- src/github-manager.ts
- typings/sander.d.ts
As discussed in #43: add a configuration option to allow the user to specify a custom PR description.
I took the liberty to also add an option to write a multi-line description by launching the git editor, that would suit my use case better than a single-line description.
> feat: allow pr body input via dialog or git editor

- package.json
When executing setup commands (github token or enterprise token) the
extension is activated
Closes #126
> fix: activate extension by setup commands

- src/status-bar-manager.ts
If not on a pull request branch the default action is now to checkout a
pull request. Also this adds a tooltip to the icon.
Closes #104
> feat: add action to status bar

- src/git.ts
Makes a slight tweak to the GitHub URL regex pattern.
The host/path separator in GitHub URLs can be `:` or `:/`, the existing character class `[:/]` only allows the matching of one of `:` or `/`, not both together.
eg. Both `git@github.com:jimcroft/vscode-github.git` and `git@github.com:/jimcroft/vscode-github.git` are valid URLs for git clone but the regex doesn't currently allow the latter (`/` on it's own isn't valid)
This PR addresses that.
> Fix github url regex pattern

- src/git.ts
- src/github-manager.ts
- test/extension.test.ts
Github Enterprise might be available on non-ssl connections
Closes #158
> feat: add support for http with github enterprise

- src/commands/token.ts
- src/extension.ts
- src/github-manager.ts
- src/tokens.ts
- test/extension.test.ts
To support different git providers (e.g. gitlab) migrate the token
storage to keep the information to which provider the token belongs.
Preparation for #166
> feat: migrate token storage to support providers

- src/commands/pull-requests.ts
I'm not a fan of picking out typos, but I hope this helps!
> fix: typo in pull request warning

- src/workflow-manager.ts
According to [Github Api ](https://developer.github.com/v3/pulls/) mergeable property is only included in single pull request call not list call. Changed so getPullRequestForCurrentBranch after makes list call makes a another call to Github Api to get the latest single Pull Request.
> Fix for mergeable status

- src/commands/token.ts
- src/helper.ts
Parse hostname from given input. This allows for either real hostnames or urls to select a hostname from.
Closes #208
> fix: parse hostname

- src/provider/client.ts
- src/provider/github/client.ts
- src/provider/github/index.ts
- src/provider/github/pull-request.ts
- src/provider/github/user.ts
- src/provider/gitlab/api.ts
- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/user.ts
- src/provider/pull-request.ts
- src/provider/user.ts
- src/workflow-manager.ts
Add and remove assignees from merge requests in gitlab.
This includes a complete user api for github and gitlab.
> feat: add/remove assignees for gitlab

- src/status-bar-manager.ts
Reschedule status update before updating. So every failure during update will not terminate the refresh.
> fix: reschedule status update

- src/provider/github/index.ts
- src/provider/gitlab/api.ts
Reponse decoder should allow reponse codes between 200 and 300.
> fix: parse response codes above 200

- src/git.ts
If first commit on current branch could not be determined then master is taken as fallback.
This assumes that the commits to put into the pull request are commit on master and then a branch is created. It will be inaccurate to chose the correct title and body if there are multiple commits on master, since it is impossible to select the first commit (maybe it would be good to diff against origin/master and select the first commit between orgin/master and master in that case).
Closes #114
> fix: unable to determine first commit

- README.md
Updated README with steps to open the command palette in VSCode to enter the GitHub Personal Access Token.
> Updated README to clarify how to enter GitHub Personal Access Token

- src/git.ts
- src/workflow-manager.ts
UI input do not belong into the git handler, therefore
the code was restructured to live in the workflow
handler.
> refactor: move manual input of pr title

- package.json
- src/configuration.ts
- src/git.ts
Instead of use hardcoded 'origin' as remote name
first try to calculate it by looking up the
proper git refs.
Closes #407
> feat: calculate git remote name

- src/status-bar-manager.ts
In the case of opening code and then afterwards change to
workspace folder without reload of vscode, it is possibel
to have colors slip through the disabled status.
Now we are resetting the colors to undefined if disabled.
Closes #301
> fix: uncolored statusbar

- src/commands/pull-requests.ts
- src/git.ts
- src/provider/github/api.ts
- src/provider/github/client.ts
- src/provider/github/pull-request.ts
- src/provider/github/repository.ts
- src/provider/gitlab/client.ts
- src/provider/gitlab/merge-request.ts
- src/provider/gitlab/repository.ts
- src/provider/pull-request.ts
- src/provider/repository.ts
This case enables external pull requests (from forked repo
without write permission) to be checked out for review.
For security reasons the user needs to confirm to pull
external code (it could be harmful to pull code if watch
tasks are running over external code).
Closes #258
> feat: detect external pull request and allow to pull it

- src/provider/github/api.ts
This PR adds `new` keyword explicitly on `LRUCache` instance creation.
This is done because in some environments implicit instance creation fails with following error:
```
Error: Class constructor LRUCache cannot be invoked without 'new'
```
> fix: create instance of LRUCache properly

- .travis.yml
Since vscode itself uses node 10 and fails to install in a node 7
environment we need to update.
> chore: use node 10 for testing

- src/commands/browse.ts
This PR uses the start line of the selection, rather than the current line, in the URL generated for the `Browse current file` command. This change is because previously this would only work as expected for multi line selections if the selection was made bottom to top (so `endLine` was the start of the selection, and `line` was the end of the selection) but not top to bottom (where `line` and `endLine` would be the same.
> fix: Browse command with Multi-Line selection

- src/git.ts
My remote is `origin`.
So the first command `git config --local --get remote.upstream.url` doesn't return anything (because I don't have a remote named `upstream`).
After that, the second command `git config --local --get-regexp ^remote.*.url` should find my remote... but it fails.
If I try to run it in zsh, I get:
```
zsh: no matches found: ^remote.*.url
```
I need to surround the regex with quotation marks so that zsh does not interpret the regex.
> Fix remote regex for zsh

- src/git.ts
**TLDR:** I'm afraid what I did in #774 was useless and, worst, adds a bug. So I'm here to revert this.
It was a misunderstanding of mine. I didn't know the `github.remoteName` setting. And when I saw the error I was mentionning in #774, I directly tried the exact same command in my zsh shell, and it didn't work. So I thought zsh was the problem and it indeed worked in zsh when I added quotation marks around the regex. But `execa` does not use zsh under the hood, so this is useless.
I just did a test with basic JavaScript using `execa` and adding quotation marks make the command crash!
```js
const execa = require('execa');
async function execute(cmd) {
const [git, ...args] = cmd.split(' ');
return execa(git, args);
}
async function getRemoteNames() {
const remotes = (await execute(
`git …
```
> Revert #774 and change user message

- src/workflow-manager.ts
The `Browse current file` command is broken on windows machines.
For example, when I run the command for the file in question, it takes me to:
```none
https://github.com/KnisterPeter/vscode-github/blob/master/%5Csrc%5Cworkflow-manager.ts#L1:L1
```
Which, when decoded, is built like this:
```none
https://github.com/KnisterPeter/vscode-github/blob/master/\src\workflow-manager.ts#L1:L1
```
Because the file path in windows is like this:
```none
\src\workflow-manager.ts#L1:L1
```
Which means it misses the check to removing the opening slash, but also, github does not accept backslashes when routing to files.
It should be safe to convert any and all backslashes to forward slashes on any OS to represent directories.
----
_Alternatively_, when grabbing the file path in the first place here: …
> Fix path format for Windows OS
